# Generated by Django 5.0.3 on 2026-04-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='PDF file of the book (max 100MB)', max_length=500, null=True, upload_to='library/pdfs/'),
        ),
    ]
